### ISSUE TITLE
[bug] zsh shell completion throw error

### ISSUE THREAD

**Issue by sunny0826** [sunny0826/kubecm#296]
Hi, i noticed this issue is only for fish and powershell but I have some problems with completion also on zsh.
For example on tab after `kubecm ` I get that last option:
```
11:32  76% ❯ kubecm
add                                                            -- Add KubeConfig to $HOME/.kube/config
alias                                                          -- Generate alias for all contexts
clear                                                          -- Clear lapsed context, cluster and user
completion                                                     -- Generate completion script
create                                                         -- Create new KubeConfig(experiment)
delete                                                         -- Delete the specified context from the kubeconfig
help                                                           -- Help about any command
list                                                           -- List KubeConfig
merge                                                          -- Merge the KubeConfig files in the specified directory
namespace                                                      -- Switch or change namespace interactively
rename                                                         -- Rename the contexts of kubeconfig
switch                                                         -- Switch Kube Context interactively
version                                                        -- Print version info
:4                                                             Completion ended with directive: ShellCompDirectiveNoFileComp
```
It also happen with any other commands but the error is sometime different:
```
11:32  76% ❯ kubecm list
:0                                                          Completion ended with directive: ShellCompDirectiveDefault
```

I enabled the completion with `kubecm completion zsh > "${fpath[1]}/_kubecm"` and zsh version is `zsh 5.8 (x86_64-ubuntu-linux-gnu)`, don't know if it matters but I also use oh-my-zsh.

_Originally posted by @gpstuff in https://github.com/sunny0826/kubecm/issues/76#issuecomment-1096456342_

**Comment by sunny0826** [comment]
@gpstuff thx for you feedback

**Comment by burmanm** [comment]
This is a bug in the cobra completions, not in kubecm. I created a ticket and a PR..

https://github.com/spf13/cobra/issues/1667

**Comment by marckhouzam** [comment]
The problem is probably that `kubecm` redirects stderr to stdout, which will break the shell completion system.
This has happened to others before 😄.  
I believe this happens here: https://github.com/sunny0826/kubecm/blob/ba2a5393435edb9008eb712cc82e3194725bd1c2/cmd/root.go#L53
The `SetOutput()` function sets stderr and stdout to point to the same place.  That function is deprecated in favor of the two functions `SetOut()` and `SetErr()` as you can see here: https://github.com/spf13/cobra/blob/master/command.go#L250-L268

If you really want to have stderr print to stdout, then you need to change it just for the `__complete` command within a `PersistentPreRun`
 
You can see some documentation about this here: https://github.com/spf13/cobra/blob/master/shell_completions.md#debugging

Making this difference between stderr and stdout for shell completion allows to print debugging information to stderr without breaking the completion scripts.

**Comment by sunny0826** [comment]
@marckhouzam @burmanm Thx for your feedback, this should be a historical problem and I will try to fix this issue.
